# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PstTable',
        ),
    ]
