# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committe',
            name='value',
            field=models.TextField(default='lol'),
        ),
    ]
