# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_committe_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('tasks', models.IntegerField()),
                ('committe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.committe')),
            ],
        ),
    ]
